/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.maxbauer.photoalbum;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int Peru=0x7f050000;
        public static final int Tan=0x7f050001;
        public static final int black=0x7f050002;
        public static final int white=0x7f050003;
    }
    public static final class dimen {
        public static final int activity_horizontal_margin=0x7f060000;
        public static final int activity_vertical_margin=0x7f060001;
    }
    public static final class drawable {
        public static final int border=0x7f020000;
        public static final int castart=0x7f020001;
        public static final int clapton=0x7f020002;
        public static final int eastlansing=0x7f020003;
        public static final int fall=0x7f020004;
        public static final int jack=0x7f020005;
        public static final int mountain=0x7f020006;
        public static final int paradise=0x7f020007;
        public static final int powell=0x7f020008;
        public static final int sanfran=0x7f020009;
        public static final int town=0x7f02000a;
        public static final int xxend=0x7f02000b;
    }
    public static final class id {
        public static final int action_settings=0x7f0a0002;
        public static final int imageView=0x7f0a0001;
        public static final int next=0x7f0a0000;
    }
    public static final class layout {
        public static final int activity_view_photos=0x7f040000;
    }
    public static final class menu {
        public static final int menu_view_photos=0x7f090000;
    }
    public static final class mipmap {
        public static final int ic_launcher=0x7f030000;
    }
    public static final class string {
        public static final int AutoScroll=0x7f070000;
        public static final int action_settings=0x7f070001;
        public static final int app_name=0x7f070002;
        public static final int bck=0x7f070003;
        public static final int hello_world=0x7f070004;
        public static final int nxt=0x7f070005;
        public static final int stopScroll=0x7f070006;
    }
    public static final class style {
        public static final int AppTheme=0x7f080000;
    }
}
